CREATE TABLE Plans (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Finished BIT NOT NULL
);

CREATE TABLE PlanActivities (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PlanId UNIQUEIDENTIFIER NOT NULL,
    ActivityId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (PlanId) REFERENCES Plans(Id) ON DELETE CASCADE
);

CREATE TABLE [dbo].[PlanDate] (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    PlanId UNIQUEIDENTIFIER NOT NULL,
    Date DATETIME2 NOT NULL,
    FOREIGN KEY (PlanId) REFERENCES Plans(Id) ON DELETE CASCADE
);
