CREATE DATABASE PlanDatabase;
USE PlanDatabase;

CREATE TABLE Plans (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Description TEXT NULL,
    Finished BOOLEAN NOT NULL
);

CREATE TABLE PlanActivities (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    PlanId CHAR(36) NOT NULL,
    ActivityId CHAR(36) NOT NULL,
    FOREIGN KEY (PlanId) REFERENCES Plans(Id) ON DELETE CASCADE
);

CREATE TABLE PlanDate (
    Id CHAR(36) NOT NULL PRIMARY KEY,
    PlanId CHAR(36) NOT NULL,
    Date DATETIME NOT NULL,
    FOREIGN KEY (PlanId) REFERENCES Plans(Id) ON DELETE CASCADE
);
